version: '3.3'

services:
  product-api:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql-product-db
  mysql-product-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: product
      MYSQL_ROOT_PASSWORD: 190518af
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - product-db:/var/lib/mysql
volumes:
  product-db: