version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: product-api
    ports:
      - "3002:3002"
    expose:
      - "3002"
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres-auth-db

  postgres-auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin2024"
    ports:
      - "5432:5432"
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/postgresql/data

volumes:
  my-db:
